### sendAllMails
POST {{host}}/api/sendValidationMails
x-functions-key: {{functions_key}}

###
POST {{host}}/api/validate/7526
x-functions-key: {{functions_key}}

###
POST {{host}}/api/validateAll
x-functions-key: {{functions_key}}
x-functions-key: {{functions_key}}

###
GET {{host}}/api/employee?name=Heinrich
x-functions-key: {{functions_key}}

###
GET {{host}}/api/employee/1483/onepager
x-functions-key: {{functions_key}}

###
GET {{host}}/api/employee/1483/onepager/Heinrich%2C%20Daniel_DE_220125.pptx
x-functions-key: {{functions_key}}

###
GET {{host}}/api/employee/1483/onepager/Heinrich,%20Daniel_DE_220125.pptx/photo/image1.jpg
x-functions-key: {{functions_key}}

###
GET {{host}}/api/employee/1483/onepager/Heinrich%2C%20Daniel_DE_220125.pptx/download
x-functions-key: {{functions_key}}
