name: CI

on:
  push:
  pull_request:

env:
  NODE_VERSION: '22.x'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure-functions'

jobs:
  check-functions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'

    concurrency:
        group: 'SharePointTest' # Tests act on a real SharePoint-Repo, so they must not be run concurrently.

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
            SHAREPOINT_CLIENT_ID: "1621d264-a7bb-40b6-bfef-9b2839cb7eec"
            SHAREPOINT_TENANT_ID: "52497ec2-0945-4f55-8021-79766363dd96"
            SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: JEST Tests
          path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/reports/jest-*.xml'
          reporter: jest-junit

  check-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
          directory: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/infra'
          framework: bicep
          soft_fail: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3

        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif
