name: reviewdog with es lint and tsc
on: [pull_request]
<<<<<<< HEAD

env:
  NODE_VERSION: '22.x'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure-functions'

permissions:
  contents: read

jobs:
  tsc:
    name: tsc reviewdog
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
            node-version: ${{ env.NODE_VERSION }}
            cache: 'npm'
            cache-dependency-path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/package-lock.json'
      - name: Install eslint save-dev
        run: |
            npm ci
            npm install eslint -D
      - uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd # v1.33.2
        with:
          reporter: github-pr-review
          eslint_flags: "src/"
